xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework2\android\os\statistics\E2EScenario*.smali .\src\ANXGallery\smali_classes3\android\os\statistics\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework2\android\provider\MiuiSettings*.smali .\src\ANXGallery\smali_classes3\android\provider\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miuisystem\android\provider\SystemSettings*.smali .\src\ANXGallery\smali_classes3\android\provider\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework2\com\android\internal\app\IPerfShielder*.smali .\src\ANXGallery\smali_classes3\com\android\internal\app\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\com\miui\daemon\performance\PerfShielderManager*.smali .\src\ANXGallery\smali_classes3\com\miui\daemon\performance\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miuisystem\com\miui\internal\cust\PrivateConfig*.smali .\src\ANXGallery\smali_classes3\com\miui\internal\cust\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miuisystem\com\miui\internal\cust\PrivateWaterMarkerConfig*.smali .\src\ANXGallery\smali_classes3\com\miui\internal\cust\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miui\com\miui\internal\os\Native*.smali .\src\ANXGallery\smali_classes3\com\miui\internal\os\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\miui\hardware\display\DisplayFeatureManager*.smali .\src\ANXGallery\smali_classes3\miui\hardware\display\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\miui\hardware\display\DisplayFeatureServiceProxy*.smali .\src\ANXGallery\smali_classes3\miui\hardware\display\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\miui\hardware\display\IDisplayFeatureCallback*.smali .\src\ANXGallery\smali_classes3\miui\hardware\display\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\miui\maml\animation\interpolater\*.smali .\src\ANXGallery\smali_classes3\miui\maml\animation\interpolater\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miuisystem\miui\os\Build*.smali .\src\ANXGallery\smali_classes3\miui\os\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\miui\os\DeviceFeature*.smali .\src\ANXGallery\smali_classes3\miui\os\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miui\miui\reflect\*.smali .\src\ANXGallery\smali_classes3\miui\reflect\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miui\miui\util\concurrent\*.smali .\src\ANXGallery\smali_classes3\miui\util\concurrent\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miuisystem\miui\util\FeatureParser*.smali .\src\ANXGallery\smali_classes3\miui\util\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miui\miui\util\IOUtils*.smali .\src\ANXGallery\smali_classes3\miui\util\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miui\miui\util\Pools*.smali .\src\ANXGallery\smali_classes3\miui\util\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\miui\util\ReflectionUtils*.smali .\src\ANXGallery\smali_classes3\miui\util\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-miui\miui\view\animation\*.smali .\src\ANXGallery\smali_classes3\miui\view\animation\
xcopy G:\Downloads\Android\systemcephy9627deodex\boot-framework3\miui\R*.smali .\src\ANXGallery\smali_classes3\miui\